### PR TITLE
Adding in test suite definition and pre-merge

### PR DESCRIPTION
**Pull request by glemieux**
This PR pre-merges fates_next_api (specifically the commit that points to `sci.1.35.0_api.10.0.0`) and adds a test definition for the Fates Fixed Biogeography mode by setting `use_fates_fixed_biogeog=.true.`.

UPDATE: test is running and catching a failure in the PR branch code.  OK to merge.

### CODE REVIEW

**Comment by glemieux** [comment]
@rosiealice the `user_nl_clm` file right now doesn't add in any special output to the test run; it's just pointing to FatesColdDef's user namelist and using those settings.  Here they are for quick reference:

https://github.com/rosiealice/ctsm/blob/de3f153c93bb8872bf1f7bb90f7291450279ea31/cime_config/testdefs/testmods_dirs/clm/FatesColdDef/user_nl_clm#L1-L10

Note that I used FatesColdDef as it's kind of the default way most of the tests are setup.  Do you want to change the `user_nl_clm` settings in anyway?  Do you want to add any output variables?  Should `use_fates_spitfire` be used?

Also, do you want to change the test duration or the grid size in any way?  Again I just copied a common test suite setup:
https://github.com/rosiealice/ctsm/blob/fba63d9b93fb67b06cd85c0aabc24bb44450df95/cime_config/testdefs/testlist_clm.xml#L1972

**Comment by glemieux** [comment]
I had some trouble getting the regression test to run, but it's (technically) working now.  The test was failing here on the fates side of things here:
https://github.com/rosiealice/fates/blob/347270b5d8182d6ff101c38d4d24f277f665b42a/main/FatesInterfaceMod.F90#L1694-L1699

I think this is because `use_nocomp` and `pass_nocomp` need to be added to the `init` procedure like `use_fates_fixed_biogeog` and `pass_biogeog` here:
https://github.com/rosiealice/ctsm/blob/de3f153c93bb8872bf1f7bb90f7291450279ea31/src/utils/clmfates_interfaceMod.F90#L328-L333
I commented out the relevant code in FatesInterfaceMod to get the test to run, but I want to make sure I'm not missing something else so I looked back at the test you posted on https://github.com/ESCOMP/CTSM/pull/985.  Looking at the `README` in that directory, it looks like the test was run on:
```
2020-04-14 11:48:26: ./create_newcase --case clm5-spfates --res f45_f45_mg37 --compset I2000Clm50Fates --run-unsupported
```
I think this means that test was run prior to the addition of the `hlm_use_nocomp` code which came in with this commit on 2020-04-19: https://github.com/NGEET/fates/pull/632/commits/2f506ccea28317ae2fd00fa551c8a178eaab4786#.  Does that sound corrrect?

I also ran a generic `f45` case using the unmodified PR branches and found it failing at the same spot in FatesInterfaceMod: 
```
/glade/scratch/glemieux/clmed-cases/pr632-ctsmpr985-simplecasecheck.fates.cheyenne.Cde3f153c-F347270b5
```
If that sounds correct I think we can merge a fix to comment out the code in FatesInterfaceMod when I deconflict PR632.

**Comment by rosiealice** [comment]
Thanks @glemieux - i've been in a virtual meeting for two days so just saw this. I'm not really sure how this works, but 
-I think I got confused between branches at some point and so added some things that should have been the first commits of the nocomp project to the fixed_biogeog branch. Apologies for that
- I think the resolution is fine for the test. It doen't need extra output, but the fates_fixed_biogeog switch should be on. 
- I guess it doesn't hurt to test with SPITFIRE either as that's a harder test...  SPITFIRE should act orthogonally to this PR, which is really just a filter on the PFTs that we allow to grow in different places.

**Comment by glemieux** [comment]
Thanks @rosiealice and no worries.  Thanks for confirming my suspicion with the branch commits and giving me feedback on the testing.  If the `use_nocomp` stuff can be left out of the fixed biogeography PR as a whole, you can go ahead and merge this (I'll comment out the `use_nocomp` stuff on the FATES side with a different PR).

FYI, I've got two more PRs coming up soon to merge into this branch and the fates PR branch to take care of the new merge conflicts that came up due to Ryan's circular dependency refactor.

**Pull request merged**
