### PR TITLE
Deconflict CTSM PR 985 with fates_next_api (commit d525994)

### PR DESCRIPTION
**Pull request by glemieux**
This PR resolves the merge conflicts that currently exist in https://github.com/ESCOMP/CTSM/pull/985.  The conflicts are due to the clmfates_interfacemod.F90 refactor that took place in https://github.com/ESCOMP/CTSM/pull/1007.

Final test check TBD once the FATES side PR https://github.com/NGEET/fates/pull/632.  I'll also have one more commit to update the Externals_CLM.xml file.

### CODE REVIEW

**Comment by glemieux** [comment]
I just looked at my regression tests of the the de-conflicted branches (both this and the FATES side) and I'm coming up with errors due to `pft_areafrac` in clmfates_interfacemod:
```
Subscript #1 of the array PFT_AREAFRAC has value 17 which is greater than the upper bound of 16
```
I haven't dug much into it yet.  Interestingly it's only happening in a subset of the regression tests.
My tests are here: 
```
/glade/u/home/glemieux/scratch/clmed-tests/PR632-CTSM985-postdeconflict-Cb5989cf9-F0ffab8bb.fates.cheyenne.intel
/glade/u/home/glemieux/scratch/clmed-tests/PR632-CTSM985-postdeconflict-Cb5989cf9-F0ffab8bb.fates.cheyenne.gnu
```

**Comment by glemieux** [comment]
@rosiealice looking into this more, I don't understand why this failure mode is showing up in some regression tests, but not others given that they are all using the same surface dataset with `lsmpft=17`.  Based on your code here:
https://github.com/ESCOMP/CTSM/pull/985/files?file-filters%5B%5D=.F90#diff-d5aa89e69afc455e4e84461df1cfa3b6R491-R498

wouldn't this always hit the upper bound of `natpft_ub=16`, which results in a `ft = 17` (assuming `natpft_lb=0`) thus going over the index here: 
https://github.com/NGEET/fates/pull/632/files#diff-7091a5fc77096a90b2a17b9bd9b5b8e0R809

Maybe I'm missing that `natpft_ub` is being calculated at smaller value somewhere else?

**Comment by rosiealice** [comment]
ah right. This one also feel foul of something I messed up around changing branches.  
https://github.com/rosiealice/ctsm/commit/cdc1b8b02bbaa8c25c4840dc7f7b8d7052b6f7d6

As in, I committed the change you correctly argue is required to fix this it to the branch I am now working on. I think I'm broadly learning that 'move fast and break things' is not the correct approach to multiple subsequent modifications...

**Comment by glemieux** [comment]
Thanks.  I'll modify this deconflict branch and test it out on one of the failing branches.

UPDATE: that worked.  Re-running the rest of the regression suite.

**Comment by glemieux** [comment]
All expected PASS:
```
/glade/u/home/glemieux/scratch/clmed-tests/PR632-CTSM985-postdeconflict-C2c3f2648-F0ffab8bb.fates.cheyenne.intel
/glade/u/home/glemieux/scratch/clmed-tests/PR632-CTSM985-postdeconflict-C2c3f2648-F0ffab8bb.fates.cheyenne.gnu
```
I think this can be merged along with https://github.com/rosiealice/fates/pull/2 and we should be good to go

**Pull request merged**
